package com.yxf.bookshop.model;
/**
 * 菜单实体类
 * @author 余晓枫，0410190109
 * 
 * */
public class Menus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.name
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.url
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.target
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.id
     *
     * @return the value of menus.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.id
     *
     * @param id the value for menus.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.name
     *
     * @return the value of menus.name
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.name
     *
     * @param name the value for menus.name
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.url
     *
     * @return the value of menus.url
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.url
     *
     * @param url the value for menus.url
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.target
     *
     * @return the value of menus.target
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.target
     *
     * @param target the value for menus.target
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.remark
     *
     * @return the value of menus.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.remark
     *
     * @param remark the value for menus.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}