package com.yxf.bookshop.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
/**
 * 消息公告实体类
 * @author 余晓枫，0410190109
 * 
 * */
public class Notices {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.title
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.detail
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String detail;

    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notices.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.id
     *
     * @return the value of notices.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.id
     *
     * @param id the value for notices.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.title
     *
     * @return the value of notices.title
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.title
     *
     * @param title the value for notices.title
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.detail
     *
     * @return the value of notices.detail
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.detail
     *
     * @param detail the value for notices.detail
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.createtime
     *
     * @return the value of notices.createtime
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.createtime
     *
     * @param createtime the value for notices.createtime
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notices.remark
     *
     * @return the value of notices.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notices.remark
     *
     * @param remark the value for notices.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}