package com.yxf.bookshop.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
/**
 * 订单实体类
 * @author 余晓枫，0410190109
 * 
 * */
public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.money
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_state
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer payState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.guest_name
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String guestName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.guest_address
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String guestAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.guest_phone
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String guestPhone;

   
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.money
     *
     * @return the value of orders.money
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.money
     *
     * @param money the value for orders.money
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_state
     *
     * @return the value of orders.pay_state
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_state
     *
     * @param payState the value for orders.pay_state
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.guest_name
     *
     * @return the value of orders.guest_name
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getGuestName() {
        return guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.guest_name
     *
     * @param guestName the value for orders.guest_name
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.guest_address
     *
     * @return the value of orders.guest_address
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getGuestAddress() {
        return guestAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.guest_address
     *
     * @param guestAddress the value for orders.guest_address
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setGuestAddress(String guestAddress) {
        this.guestAddress = guestAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.guest_phone
     *
     * @return the value of orders.guest_phone
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getGuestPhone() {
        return guestPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.guest_phone
     *
     * @param guestPhone the value for orders.guest_phone
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setGuestPhone(String guestPhone) {
        this.guestPhone = guestPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_time
     *
     * @return the value of orders.order_time
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_time
     *
     * @param orderTime the value for orders.order_time
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.remark
     *
     * @return the value of orders.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.remark
     *
     * @param remark the value for orders.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}