package com.yxf.bookshop.model;
/**
 * 订单详情实体类
 * @author 余晓枫，0410190109
 * 
 * */
public class Orderitems {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.order_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.product_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitems.buy_num
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer buyNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.order_id
     *
     * @return the value of orderitems.order_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.order_id
     *
     * @param orderId the value for orderitems.order_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.product_id
     *
     * @return the value of orderitems.product_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.product_id
     *
     * @param productId the value for orderitems.product_id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitems.buy_num
     *
     * @return the value of orderitems.buy_num
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getBuyNum() {
        return buyNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitems.buy_num
     *
     * @param buyNum the value for orderitems.buy_num
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setBuyNum(Integer buyNum) {
        this.buyNum = buyNum;
    }
}