package com.yxf.bookshop.model;

/**
 * 商品信息实体类
 * @author 余晓枫，0410190109
 * 
 * */
public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer id;
    private String name;
    private Double price;
    private String category;
    private Integer pnum;
    private String imgurl;
    private String description;
    private String remark;
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public Double getPrice() {
        return price;
    }
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getCategory() {
        return category;
    }
    public void setCategory(String category) {
        this.category = category;
    }
    public Integer getPnum() {
        return pnum;
    }
    public void setPnum(Integer pnum) {
        this.pnum = pnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.imgurl
     *
     * @return the value of products.imgurl
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.imgurl
     *
     * @param imgurl the value for products.imgurl
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.description
     *
     * @return the value of products.description
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.description
     *
     * @param description the value for products.description
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.remark
     *
     * @return the value of products.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.remark
     *
     * @param remark the value for products.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}