package com.yxf.bookshop.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
/**
 * 用户信息实体类
 * @author 余晓枫，0410190109
 * 
 * */
public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.telephone
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.introduce
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.activecode
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String activecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.state
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.role
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.registtime
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    
    
    
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Date registtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.telephone
     *
     * @return the value of users.telephone
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.telephone
     *
     * @param telephone the value for users.telephone
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.introduce
     *
     * @return the value of users.introduce
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.introduce
     *
     * @param introduce the value for users.introduce
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.activecode
     *
     * @return the value of users.activecode
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getActivecode() {
        return activecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.activecode
     *
     * @param activecode the value for users.activecode
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setActivecode(String activecode) {
        this.activecode = activecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.state
     *
     * @return the value of users.state
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.state
     *
     * @param state the value for users.state
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.role
     *
     * @return the value of users.role
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.role
     *
     * @param role the value for users.role
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.registtime
     *
     * @return the value of users.registtime
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public Date getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.registtime
     *
     * @param registtime the value for users.registtime
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRegisttime(Date registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.remark
     *
     * @return the value of users.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.remark
     *
     * @param remark the value for users.remark
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}