package com.yxf.bookshop.mapper;

import java.util.List;

import com.yxf.bookshop.model.Menus;
/**
 * 菜单Mapper,Dao层，对应同名映射文件
 * @author 余晓枫，0410190109
 * 
 * */
public interface MenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insert(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insertSelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    Menus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int updateByPrimaryKeySelective(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int updateByPrimaryKey(Menus record);
    
    //查询全部菜单信息
    List<Menus> findAllMenu();
}