package com.yxf.bookshop.mapper;

import java.util.List;

import com.yxf.bookshop.model.Orders;
/**
 * 订单Mapper,Dao层，对应同名映射文件
 * @author 余晓枫，0410190109
 * 
 * */
public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int updateByPrimaryKey(Orders record);
    
    
    List<Orders> selectAllOrders();
    int deleteById(Orders id);
    Orders selectById(Orders id);
    
}