package com.yxf.bookshop.mapper;

import com.yxf.bookshop.model.Orderitems;
/**
 * 订单详情Mapper,Dao层，对应同名映射文件
 * @author 余晓枫，0410190109
 * 
 * */
public interface OrderitemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insert(Orderitems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitems
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insertSelective(Orderitems record);
}