package com.yxf.bookshop.mapper;

import java.util.List;

import com.yxf.bookshop.model.Orders;
import com.yxf.bookshop.model.Users;
/**
 * 用户信息Mapper,Dao层，对应同名映射文件
 * @author 余晓枫，0410190109
 * 
 * */
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Mon May 24 18:37:14 CST 2021
     */
    int updateByPrimaryKey(Users record);
    
    //通过用户名查询用户
    Users selectByUserName(Users user);
    
    List<Users> selectAllUsers();
    int deleteById(Users id);
    Users selectById(Users id);
}